<div class="scroll">
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
    <div class="box">10</div>
</div>
<style>
    .scroll {
        display: flex;
        flex-direction: row;
        overflow-x: scroll;
    }

    .box {
        height: auto;
        min-width: 10%;
    }
</style>